module Data.All where

open import Data.Fin using (zero; suc)
open import Data.List using (List; []; _∷_; lookup)
open import Level using (Level)

private
  variable
    ℓ ℓ' : Level
    α    : Set ℓ
    x    : α
    xs   : List α
    f    : α → Set ℓ

-- The conjunction of a list of types
-- generated by applying an indexing function to a list of type indices.
data All (f : α → Set ℓ') : List α → Set ℓ' where
  []  : All f []
  _∷_ : f x → All f xs → All f (x ∷ xs)

-- Retrieve a component from the conjunction.
project : All f xs → ∀ i → f (lookup xs i)
project (y ∷ _)  zero    = y
project (_ ∷ ys) (suc i) = project ys i
